import lyrics from "../../../public/songs/green-boys/data/lyrics.json";
import translations from "../../../public/songs/green-boys/data/translations.json";

export const FPS = 60;
export const DURATION = Math.ceil((lyrics.durationMs * FPS) / 1000);
export const LINES = lyrics.lines
  .filter((l) => l.kind === "lyric")
  .map((l, i) => ({ ...l, index: i, translation: translations.lines[i] }));
export const P = {
  pine: "#173D35",
  leaf: "#72AD69",
  sky: "#91C8DE",
  sun: "#F2CD68",
  clay: "#AE493C",
  cloud: "#F2F6EE",
};
export type Theme = {
  surface: string;
  ink: string;
  primary: string;
  secondary: string;
  translation: string;
};
export const THEMES: Record<string, Theme> = {
  cloud: {
    surface: P.cloud,
    ink: P.pine,
    primary: P.clay,
    secondary: "#315F4F",
    translation: P.pine,
  },
  pine: {
    surface: P.pine,
    ink: P.cloud,
    primary: P.sun,
    secondary: P.sky,
    translation: P.cloud,
  },
  sky: {
    surface: "#DCEEF2",
    ink: P.pine,
    primary: "#913C36",
    secondary: "#294F7B",
    translation: P.pine,
  },
  leaf: {
    surface: "#DCE9C8",
    ink: P.pine,
    primary: "#8F3833",
    secondary: "#3C527A",
    translation: P.pine,
  },
  earth: {
    surface: "#6A302D",
    ink: P.cloud,
    primary: P.sun,
    secondary: "#CDE7D2",
    translation: P.cloud,
  },
};
export type Shot = {
  key: string;
  lines: number[];
  theme: string;
  note: string;
  x: number;
  y: number;
  accent: string[];
  inner?: boolean;
};
export const SHOTS: Shot[] = [
  {
    key: "window",
    lines: [0, 1],
    theme: "cloud",
    x: 112,
    y: 188,
    accent: ["何で", "僕", "抜けたい"],
    inner: true,
    note: "雨窗汇水，窗扇打开，门外出现通路",
  },
  {
    key: "lockers",
    lines: [2, 3],
    theme: "sky",
    x: 140,
    y: 230,
    accent: ["無駄", "逃げ", "比べ"],
    note: "更衣柜倒影互相遮挡，柜门打开露出自己的鞋",
  },
  {
    key: "startline",
    lines: [4, 5],
    theme: "pine",
    x: 108,
    y: 186,
    accent: ["初め", "一緒", "分か"],
    note: "多条跑道汇到同一起点，起点灯带依次点亮",
  },
  {
    key: "gate",
    lines: [6, 7],
    theme: "leaf",
    x: 120,
    y: 218,
    accent: ["関係", "進め"],
    note: "横栏缓缓抬起，斜阳延伸至门外",
  },
  {
    key: "rain",
    lines: [8, 9],
    theme: "sky",
    x: 160,
    y: 232,
    accent: ["涙", "くやしく"],
    inner: true,
    note: "雨滴聚成池面，波纹推开倒影中的云",
  },
  {
    key: "steps",
    lines: [10],
    theme: "pine",
    x: 108,
    y: 265,
    accent: ["歩み", "変われ"],
    note: "阶梯上方的光连续揭开更高一级台阶",
  },
  {
    key: "grass",
    lines: [11, 12],
    theme: "cloud",
    x: 126,
    y: 210,
    accent: ["何度", "立ち上が"],
    note: "草叶被风吹弯又恢复，后句触发一株新芽展开",
  },
  {
    key: "bridge",
    lines: [13, 14],
    theme: "pine",
    x: 112,
    y: 214,
    accent: ["越え", "信じ"],
    note: "溪流下行，桥板依次展开连接对岸",
  },
  {
    key: "laces",
    lines: [15, 16],
    theme: "leaf",
    x: 140,
    y: 182,
    accent: ["何度", "立ち上が"],
    note: "鞋带收紧成结，鞋尖指向门外的阳光",
  },
  {
    key: "sign",
    lines: [17],
    theme: "sky",
    x: 120,
    y: 255,
    accent: ["諦めない", "道標"],
    note: "岔路标牌转向远方，云影越过延伸的河堤",
  },
  {
    key: "curtain",
    lines: [18, 19],
    theme: "cloud",
    x: 126,
    y: 215,
    accent: ["不安", "勇気"],
    inner: true,
    note: "窗帘被风撑起，后句让帘后窗锁松开",
  },
  {
    key: "storm",
    lines: [20, 21],
    theme: "pine",
    x: 110,
    y: 207,
    accent: ["雨", "風", "進む", "近づ"],
    note: "风雨扫过山道，远端路灯逐盏出现",
  },
  {
    key: "bowl",
    lines: [22, 23],
    theme: "sky",
    x: 126,
    y: 186,
    accent: ["痛み", "失望", "受け入"],
    inner: true,
    note: "雨滴落进陶碗，水面逐渐平静并倒映一片新绿",
  },
  {
    key: "house",
    lines: [24, 25],
    theme: "leaf",
    x: 108,
    y: 194,
    accent: ["明日", "笑え", "未完成"],
    note: "未封顶的屋子透入光束，一块新的屋瓦滑入空位",
  },
  {
    key: "kite",
    lines: [26],
    theme: "cloud",
    x: 126,
    y: 248,
    accent: ["掴み", "笑い"],
    note: "系在木桩上的风筝升起，绳索张开通向天空",
  },
  {
    key: "fence",
    lines: [27, 28],
    theme: "pine",
    x: 144,
    y: 230,
    accent: ["限界", "誰", "決め"],
    note: "近处栅栏向两侧开启，完整跑道显露出来",
  },
  {
    key: "breakwater",
    lines: [29, 30],
    theme: "sky",
    x: 116,
    y: 180,
    accent: ["何度", "立ち向か"],
    note: "海浪扑向防波堤，灯塔光线扫出安全的航道",
  },
  {
    key: "mud",
    lines: [31, 32],
    theme: "earth",
    x: 140,
    y: 212,
    accent: ["姿", "ガムシャラ"],
    note: "泥点落在训练鞋旁，水滴洗出鞋底的轮廓",
  },
  {
    key: "tree",
    lines: [33, 34],
    theme: "cloud",
    x: 126,
    y: 190,
    accent: ["何度", "立ち向か"],
    note: "树冠顺风回摆，后句让枝梢的一簇新叶展开",
  },
  {
    key: "stones",
    lines: [35, 36],
    theme: "pine",
    x: 116,
    y: 205,
    accent: ["越え", "進も"],
    note: "溪水绕过石头，后句露出下一块可踏的石面",
  },
  {
    key: "switchback",
    lines: [37, 38],
    theme: "sky",
    x: 130,
    y: 184,
    accent: ["悲しみ", "遠回り"],
    inner: true,
    note: "山路绕到岩壁背后，第二句揭开被遮挡的出口",
  },
  {
    key: "coat",
    lines: [39, 40],
    theme: "cloud",
    x: 110,
    y: 194,
    accent: ["途中", "自分", "抱き"],
    inner: true,
    note: "长椅上的外套被风展开，袖子自然合拢包住围巾",
  },
  {
    key: "prints",
    lines: [41, 42],
    theme: "leaf",
    x: 148,
    y: 220,
    accent: ["大丈夫", "足跡"],
    note: "湿地脚印逐步延伸，旧脚印内长出细小草芽",
  },
  {
    key: "crossing",
    lines: [43],
    theme: "pine",
    x: 126,
    y: 270,
    accent: ["道", "進ん"],
    note: "铁路栏杆抬起，轨道对侧的通路完整显露",
  },
  {
    key: "canopy",
    lines: [44, 45],
    theme: "leaf",
    x: 112,
    y: 194,
    accent: ["何度", "立ち上が"],
    note: "林冠两边摇开，远处的天空由窄缝变开阔",
  },
  {
    key: "bleachers",
    lines: [46],
    theme: "sky",
    x: 126,
    y: 264,
    accent: ["大きな", "笑い"],
    note: "看台上的彩旗依次扬起，阳光扫过空座位",
  },
  {
    key: "dandelion",
    lines: [47, 48],
    theme: "cloud",
    x: 116,
    y: 215,
    accent: ["何度", "立ち上が"],
    note: "蒲公英从俯伏抬起，第二句放飞成熟种子",
  },
  {
    key: "relay",
    lines: [49, 50],
    theme: "earth",
    x: 132,
    y: 190,
    accent: ["情熱", "ぶつけ"],
    note: "接力棒沿交接线向前滑动，触发远方接力区亮起",
  },
  {
    key: "track",
    lines: [51],
    theme: "pine",
    x: 110,
    y: 260,
    accent: ["何度", "走り"],
    note: "俯视弯道掠过，前方直道在长影之间展开",
  },
  {
    key: "door",
    lines: [52, 53],
    theme: "sky",
    x: 126,
    y: 210,
    accent: ["見え", "アナタ"],
    note: "门缝显出远处田野，门扇转开后视线延伸到地平线",
  },
  {
    key: "ridge",
    lines: [54, 55],
    theme: "pine",
    x: 120,
    y: 182,
    accent: ["何度", "挑め"],
    note: "高处山脊露出连续足点，远景云层向两边让开",
  },
  {
    key: "fork",
    lines: [56, 57],
    theme: "leaf",
    x: 108,
    y: 192,
    accent: ["自分", "決め", "逃げ"],
    note: "两个方向的路径并列，选定方向后远处指示旗展开",
  },
  {
    key: "horizon",
    lines: [58, 59],
    theme: "cloud",
    x: 116,
    y: 210,
    accent: ["GREEN", "BOY", "挑み"],
    note: "嫩叶在近景展开，远方道路持续朝明亮天空延伸",
  },
];
export const startFrame = (shot: Shot) =>
  Math.round((LINES[shot.lines[0]].startMs * FPS) / 1000);
